on: 
  workflow_dispatch:
name: Download OS101 Source
jobs:
  wget:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: List files in the repo before deleting target
        run: ls
      - name: Delete target folder
        run: rm -rf download
      - name: List files in the repo after deleting target
        run: ls
      - name: Create target folder
        run: mkdir download
      - name: List files in the repo after creating target
        run: ls
      - name: Change directory into target
        run: |
          cd download
          touch readme.md
          wget https://raw.githubusercontent.com/nasa/Transform-to-Open-Science/open-science-101/README.md -O readme.md
          mkdir Module_1
          mkdir Module_2
          mkdir Module_3
          mkdir Module_4
          mkdir Module_5
          touch Module_1/readme.md
          touch Module_2/readme.md
          touch Module_3/readme.md
          touch Module_4/readme.md
          touch Module_5/readme.md
      - name: Commit and push changes
        run: |
          git config --global user.name "bressler95tops"
          git config --global user.email "briancressler@gmail.com"

          git add -A
          git commit -m "commit message"
          git push
